# Generated by Django 5.0.6 on 2024-07-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shortened_url',
            field=models.TextField(default=None, unique=True),
            preserve_default=False,
        ),
    ]
