# Generated by Django 5.0.6 on 2024-07-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_url_shortened_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortened_url', models.TextField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='url',
            name='shortened_url',
        ),
    ]
