# Generated by Django 5.0.1 on 2024-07-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_shortenedurl_remove_url_shortened_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShortenedUrl',
        ),
        migrations.AddField(
            model_name='url',
            name='shortened_url',
            field=models.TextField(null=True, unique=True),
        ),
    ]
